#!/usr/bin/env bash
#
# coredns-installer.sh
#   Installs the CoreDNS docker container
#


set -euo pipefail

SOURCE_SCRIPT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd -- "${SOURCE_SCRIPT}/../.." && pwd)"

# shellcheck source=../../lib/common.sh
source "${REPO_ROOT}/lib/common.sh" || {
    printf '\033[1;31m[x]\033[0m cannot source %s/lib/common.sh\n' "${REPO_ROOT}" >&2
    exit 1
}

COMPOSE_FILE="${SOURCE_SCRIPT}/docker-compose.yml"
RESOLVED_DIR="/etc/systemd/resolved.conf.d"
RESOLVED_DROPIN="${RESOLVED_DIR}/lab-dns.conf"
ZONE_TEMPLATE="${SOURCE_SCRIPT}/zones/lab.test.zone.tmpl"
ZONE_FILE="${SOURCE_SCRIPT}/zones/lab.test.zone"
ENV_FILE="${SOURCE_SCRIPT}/.env"

render_config() {
    local cloudbr0_ip
    local zone_serial

    cloudbr0_ip="$(get_cloudbr0_ip)"
    zone_serial="$(date -u +%s)"

    cat > "$ENV_FILE" << EOF
# Generated by coredns-installer.sh - do not edit.
# Regenerate: sudo ./services/coredns/coredns-installer.sh
CLOUDBR0_IP=${cloudbr0_ip}
EOF

    CLOUDBR0_IP="$cloudbr0_ip" \
    ZONE_SERIAL="$zone_serial" \
    envsubst '${CLOUDBR0_IP} ${ZONE_SERIAL}' \
        < "$ZONE_TEMPLATE" \
        > "$ZONE_FILE"

    log "Environment file rendered: ${ENV_FILE}"
    log "CoreDNS zone rendered: ${ZONE_FILE}"
}

configure_resolved() {
    local cloudbr0_ip

    cloudbr0_ip="$(get_cloudbr0_ip)"

    log "Configuring systemd-resolved for lab.test"

    install -d -m 0755 "${RESOLVED_DIR}"

    cat > "${RESOLVED_DROPIN}" <<EOF
[Resolve]
DNS=${cloudbr0_ip}
Domains=~lab.test
EOF

    chmod 644 "${RESOLVED_DROPIN}"

    systemctl restart systemd-resolved ||
        die "Failed to restart systemd-resolved"

    log "lab.test DNS routing configured"

}

start_coredns() {
    log "Starting CoreDNS"
    docker compose -f "${COMPOSE_FILE}" up -d --remove-orphans
}

main() {
    verify_root
    render_config
    start_coredns
    configure_resolved
    log "CoreDNS ready"
}

main "$@"