name: coredns

services:
  coredns:
    image: coredns/coredns:1.14.7
    container_name: coredns
    restart: unless-stopped
    
    command:
      - -conf
      - /etc/coredns/Corefile
    
    ports:
      - "${CLOUDBR0_IP:?not set - run services/coredns/coredns-installer.sh}:53:53/udp"
      - "${CLOUDBR0_IP:?not set - run services/coredns/coredns-installer.sh}:53:53/tcp"
    
    volumes:
      - ./Corefile:/etc/coredns/Corefile:ro
      - ./zones:/etc/coredns/zones:ro